# Generated by Django 5.1.15 on 2026-02-27 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinFlipChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('flip_result', models.CharField(blank=True, choices=[('heads', 'Heads'), ('tails', 'Tails')], max_length=5, null=True)),
                ('challenger_choice', models.CharField(choices=[('heads', 'Heads'), ('tails', 'Tails')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coinflip_challenges_sent', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coinflip_challenges_received', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coinflip_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'games_gamechallenge',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='games_gamec_status_bbca0b_idx')],
            },
        ),
    ]
