# Generated by Django 5.1.15 on 2026-03-02 04:07

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinflip', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinflipchallenge',
            name='stake',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='coinflipchallenge',
            constraint=models.CheckConstraint(condition=models.Q(('stake__gte', 1)), name='coinflip_stake_positive'),
        ),
    ]
