# Generated by Django 5.1.15 on 2026-03-06 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinflip', '0002_alter_coinflipchallenge_stake_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coinflipchallenge',
            index=models.Index(fields=['challenger', 'status'], name='games_gamec_challen_4ae44b_idx'),
        ),
        migrations.AddIndex(
            model_name='coinflipchallenge',
            index=models.Index(fields=['opponent', 'status'], name='games_gamec_opponen_be5e36_idx'),
        ),
    ]
