# Generated by Django 5.1.15 on 2026-02-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
