# Generated by Django 5.1.15 on 2026-03-02 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-balance'], name='userprofile_balance_desc'),
        ),
    ]
