# Generated by Django 5.1.15 on 2026-03-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sound_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
