# Generated by Django 5.1.15 on 2026-03-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_sound_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='leaderboard_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
