# Generated by Django 5.1.15 on 2026-02-27 02:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamechallenge',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='gamechallenge',
            index=models.Index(fields=['status', 'created_at'], name='games_gamec_status_bbca0b_idx'),
        ),
    ]
