# Generated by Django 5.1.15 on 2026-03-17 04:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokerHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('preflop', 'Preflop'), ('flop', 'Flop'), ('turn', 'Turn'), ('river', 'River'), ('showdown', 'Showdown'), ('completed', 'Completed')], default='preflop', max_length=10)),
                ('dealer_seat', models.PositiveSmallIntegerField()),
                ('community_cards', models.CharField(blank=True, max_length=30)),
                ('pot', models.PositiveIntegerField(default=0)),
                ('side_pots', models.JSONField(blank=True, default=list)),
                ('player_hands', models.JSONField(blank=True, default=dict)),
                ('current_seat', models.PositiveSmallIntegerField(default=0)),
                ('current_bet', models.PositiveIntegerField(default=0)),
                ('last_raise', models.PositiveIntegerField(default=0)),
                ('winner_ids', models.JSONField(blank=True, default=list)),
                ('round_bets', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-hand_number'],
            },
        ),
        migrations.CreateModel(
            name='PokerPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.PositiveSmallIntegerField()),
                ('chips', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('folded', 'Folded'), ('all_in', 'All In'), ('eliminated', 'Eliminated'), ('spectating', 'Spectating'), ('left', 'Left')], default='active', max_length=11)),
                ('is_online', models.BooleanField(default=False)),
                ('rebuys_used', models.PositiveSmallIntegerField(default=0)),
                ('vote_end', models.BooleanField(default=False)),
                ('coins_invested', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker_seats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PokerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('fold', 'Fold'), ('check', 'Check'), ('call', 'Call'), ('bet', 'Bet'), ('raise', 'Raise'), ('all_in', 'All In'), ('post_blind', 'Post Blind')], max_length=10)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='poker.pokerhand')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='poker.pokerplayer')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PokerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('stake', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('starting_chips', models.PositiveIntegerField(default=1000)),
                ('min_players', models.PositiveSmallIntegerField(default=3)),
                ('max_players', models.PositiveSmallIntegerField(default=8)),
                ('small_blind', models.PositiveIntegerField(default=10)),
                ('big_blind', models.PositiveIntegerField(default=20)),
                ('allow_rebuys', models.BooleanField(default=False)),
                ('max_rebuys', models.PositiveSmallIntegerField(default=0)),
                ('time_per_action', models.PositiveSmallIntegerField(default=30)),
                ('hand_number', models.PositiveIntegerField(default=0)),
                ('dealer_seat', models.PositiveSmallIntegerField(default=0)),
                ('end_vote_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker_tables_created', to=settings.AUTH_USER_MODEL)),
                ('end_vote_initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pokerplayer',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='poker.pokertable'),
        ),
        migrations.AddField(
            model_name='pokerhand',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hands', to='poker.pokertable'),
        ),
        migrations.AddIndex(
            model_name='pokertable',
            index=models.Index(fields=['status', 'created_at'], name='poker_poker_status_d4f372_idx'),
        ),
        migrations.AddIndex(
            model_name='pokertable',
            index=models.Index(fields=['creator', 'status'], name='poker_poker_creator_f3432e_idx'),
        ),
        migrations.AddConstraint(
            model_name='pokertable',
            constraint=models.CheckConstraint(condition=models.Q(('stake__gte', 1)), name='poker_stake_positive'),
        ),
        migrations.AddConstraint(
            model_name='pokerplayer',
            constraint=models.UniqueConstraint(fields=('table', 'seat'), name='unique_table_seat'),
        ),
        migrations.AddConstraint(
            model_name='pokerplayer',
            constraint=models.UniqueConstraint(fields=('table', 'user'), name='unique_table_user'),
        ),
        migrations.AddConstraint(
            model_name='pokerhand',
            constraint=models.UniqueConstraint(fields=('table', 'hand_number'), name='unique_table_hand'),
        ),
    ]
