# Generated by Django 5.1.15 on 2026-03-18 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pokerplayer',
            index=models.Index(fields=['user', 'status'], name='pokerplayer_user_status'),
        ),
    ]
