# Generated by Django 5.1.15 on 2026-02-27 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chessgame',
            new_name='chess_chess_status_bbde40_idx',
            old_name='apps_chess__status_5e0f0c_idx',
        ),
    ]
