# Generated by Django 5.1.15 on 2026-03-02 04:07

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_rename_apps_chess__status_5e0f0c_idx_chess_chess_status_bbde40_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('checkmate', 'Checkmate'), ('stalemate', 'Stalemate'), ('draw', 'Draw agreed'), ('resign', 'Resignation'), ('timeout', 'Timeout'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='stake',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='chessgame',
            constraint=models.CheckConstraint(condition=models.Q(('stake__gte', 1)), name='chess_stake_positive'),
        ),
    ]
