# Generated by Django 5.1.15 on 2026-03-06 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_alter_chessgame_end_reason_alter_chessgame_stake_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chessgame',
            index=models.Index(fields=['creator', 'status'], name='chess_chess_creator_e988cd_idx'),
        ),
        migrations.AddIndex(
            model_name='chessgame',
            index=models.Index(fields=['opponent', 'status'], name='chess_chess_opponen_34bef2_idx'),
        ),
    ]
