# Generated by Django 5.1.15 on 2026-03-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0004_chessgame_chess_chess_creator_e988cd_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('checkmate', 'Checkmate'), ('stalemate', 'Stalemate'), ('draw', 'Draw agreed'), ('threefold', 'Threefold repetition'), ('fivefold', 'Fivefold repetition'), ('fifty_move', 'Fifty-move rule'), ('seventy_five', 'Seventy-five-move rule'), ('insufficient', 'Insufficient material'), ('resign', 'Resignation'), ('timeout', 'Timeout'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
    ]
