# Generated by Django 5.1.15 on 2026-03-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0005_expanded_draw_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='time_control',
            field=models.PositiveIntegerField(choices=[(60, '1 min - Bullet'), (180, '3 min - Blitz'), (300, '5 min - Blitz'), (600, '10 min - Rapid'), (1800, '30 min - Classical')], default=600),
        ),
    ]
