# Generated by Django 5.1.15 on 2026-03-02 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('trade', 'Trade'), ('mint', 'Mint'), ('game', 'Game'), ('game_win', 'Game Win'), ('game_loss', 'Game Loss')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['sender', 'tx_type', '-created_at'], name='economy_tra_sender__6e6508_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['receiver', 'tx_type', '-created_at'], name='economy_tra_receive_3eeeb6_idx'),
        ),
    ]
