# Generated by Django 5.1.15 on 2026-03-18 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_427e4b_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(condition=models.Q(('is_read', False)), fields=['user', '-created_at'], name='notif_user_unread'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notif_user_recent'),
        ),
    ]
